services:
  landingpage:
    build:
      context: .
      dockerfile: Dockerfile
    image: application-landingpage
    container_name: landingpage
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    restart: unless-stopped
